// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.Config>;

export function Greet(arg1:string):Promise<string>;

export function PostToBoth(arg1:string):Promise<string>;

export function PostToThreads(arg1:string):Promise<string>;

export function PostToTwitter(arg1:string):Promise<string>;

export function SaveConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;
