// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PostToBoth(arg1) {
  return window['go']['main']['App']['PostToBoth'](arg1);
}

export function PostToThreads(arg1) {
  return window['go']['main']['App']['PostToThreads'](arg1);
}

export function PostToTwitter(arg1) {
  return window['go']['main']['App']['PostToTwitter'](arg1);
}

export function SaveConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}
